<div class="card_gzjl">
    <div class="undergo_div">
        <div class="under_title">
            <span class="under_per">个人经历一</span>
            <span class="under_time">2016年9月20日~2016年9月21日</span>
        </div>
        <div class="under_summer">
            <p>
                这里是我的个人经历，欢迎阅读，虽然并没有什么卵用...
                这里是我的个人经历，欢迎阅读，虽然并没有什么卵用...
                这里是我的个人经历，欢迎阅读，虽然并没有什么卵用...
                这里是我的个人经历，欢迎阅读，虽然并没有什么卵用...
                这里是我的个人经历，欢迎阅读，虽然并没有什么卵用...
                这里是我的个人经历，欢迎阅读，虽然并没有什么卵用...
            </p>
        </div>
    </div>
    <div class="undergo_div">
        <div class="under_title">
            <span class="under_per">个人经历二</span>
            <span class="under_time">2016年9月20日~2016年9月21日</span>
        </div>
        <div class="under_summer">
            <p>
                这里是我的个人经历，欢迎阅读，虽然并没有什么卵用...
                这里是我的个人经历，欢迎阅读，虽然并没有什么卵用...
                这里是我的个人经历，欢迎阅读，虽然并没有什么卵用...
                这里是我的个人经历，欢迎阅读，虽然并没有什么卵用...
                这里是我的个人经历，欢迎阅读，虽然并没有什么卵用...
                这里是我的个人经历，欢迎阅读，虽然并没有什么卵用...
            </p>
        </div>
    </div>
    <div class="undergo_div">
        <div class="under_title">
            <span class="under_per">个人经历三</span>
            <span class="under_time">2016年9月20日~2016年9月21日</span>
        </div>
        <div class="under_summer">
            <p>
                这里是我的个人经历，欢迎阅读，虽然并没有什么卵用...
                这里是我的个人经历，欢迎阅读，虽然并没有什么卵用...
                这里是我的个人经历，欢迎阅读，虽然并没有什么卵用...
                这里是我的个人经历，欢迎阅读，虽然并没有什么卵用...
                这里是我的个人经历，欢迎阅读，虽然并没有什么卵用...
                这里是我的个人经历，欢迎阅读，虽然并没有什么卵用...
            </p>
        </div>
    </div>

</div>